### PR TITLE
Added python3 support and setup. This closes #37

### LINKED ISSUE #36: ImportError: cannot import name 'SOMFactory'
Hello,

I have installed sompy without any errors (https://github.com/sevamoo/SOMPY).
However when i try:

import sompy

I receive an error code:

File "C:\Anaconda3\lib\site-packages\sompy-1.0-py3.5.egg\sompy\__init__.py", line 30, in <module>
 from sompy import SOMFactory
ImportError: cannot import name 'SOMFactory'

I am using Python 3.5.1 (Anaconda 4.1.1 for Windows)
Any help or suggestions would be greatly appreciated.

Stefan

### LINKED ISSUE #37: Add python3 support and setup

### PR DESCRIPTION
**Pull request by graeme44**
Added python3 support and setup.
To install for python3 run: `python3 setup.py install`
@sevamoo, @stef8310 this would close #36.

### CODE REVIEW

**Comment by sevamoo** [comment]
@graeme44 Thanks for doing this. But did you run some tests? Specially, for visualization functions under python 3. I appreciate it a lot.

**Comment by graeme44** [comment]
@sevamoo I ran some basic tests, nothing that heavy on the visualisations though. I will test more thoroughly and add report back.

**Comment by sevamoo** [comment]
@graeme44  Thanks. Once before, I merged a similar pull request, but later we realized there were issues with visualizations. I would appreciate it if you just test the provided example here: http://goo.gl/PuRTYA
Thanks.

**Comment by graeme44** [comment]
@sevamoo: I can run all of that code in the example fine and all plots are reproduced.
There is a small issue with that example though:
`v.show(som, what='codebook', which_dim=[0,1], CMAP=None, col_sz=6)` - CMAP should be cmap.
ie. `v.show(som, what='codebook', which_dim=[0,1], cmap=None, col_sz=6)`

**Comment by stef8310** [comment]
Thanks for the fast reply and good support!

**Pull request merged**
