### PR TITLE
Add option for desnormalizing the codebook when showing the components map

### PR DESCRIPTION
**Pull request by ivallesp**
I add a parameter to the show function inside the View2D class for desnormalize the components scale. This way it is far easier to interpret the results. Example of usage:

`from sompy.visualization.mapview import View2D`
`view2D  = View2D(5,1,"rand data",text_size=7)`
`view2D.show(sm, col_sz=3, desnormalize=True)`

### CODE REVIEW

**Comment by ivallesp** [comment]
Conflict solved!

**Comment by ivallesp** [comment]
By the way, could you add me as contributor of the pulls I did? Thank you

**Comment by sevamoo** [comment]
No problem, 
Can you update those codes and include your name in the contributions on top?
Is that what you mean?

**Comment by ivallesp** [comment]
No no, just wanted to appear as author of the commit in github. It is solved :) my fault. Thank you. 

Enviado desde mi iPhone

**Comment by sevamoo** [comment]
No problem. I appreciated a lot your contributions as it was more on SOM functions rather than Pythonic aspects.  If you have a bit more contributions, definitely I will add your name. My pleasure. 
I don't think it is a big deal, but I try to be fair to other people who contributed. Look at the contributions.

**Comment by ivallesp** [comment]
Thanks for it!! I I have more time I will continue contributing. Definitely :D.

**Comment by sevamoo** [comment]
Hi @ivallesp 
I just added your name in the README file. Thanks a lot for your helps.

**Comment by ivallesp** [comment]
Wow! What a surprise, It was not necessary!! Thank you very much! 

I am really glad to help, this algorithm is very helpful to me as Data Analyst and I don't like to open Matlab every time I want to use it... I do it because of my interest :D. 

I appreciate a lot your consideration. Thanks

**Pull request merged**
